-- Customer credit notes linked to approved AR invoices (ar_invoices.status_id = 1)

CREATE TABLE IF NOT EXISTS ar_credit_notes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  credit_note_uniqid VARCHAR(64) NOT NULL,
  credit_note_number VARCHAR(64) NOT NULL,
  credit_note_date DATE NOT NULL,
  reference_no VARCHAR(128) NULL,
  subject VARCHAR(512) NULL,
  customer_id INT NOT NULL,
  ar_invoice_id INT NOT NULL COMMENT 'Source customer invoice (approved)',
  company_id INT NULL,
  warehouse_id INT NULL,
  currency_id INT NULL,
  customer_notes TEXT NULL,
  discount_type VARCHAR(16) NOT NULL DEFAULT 'fixed',
  discount_amount DECIMAL(18,4) NOT NULL DEFAULT 0,
  subtotal DECIMAL(18,4) NOT NULL DEFAULT 0,
  tax_total DECIMAL(18,4) NOT NULL DEFAULT 0,
  total DECIMAL(18,4) NOT NULL DEFAULT 0,
  status_id INT NOT NULL DEFAULT 3 COMMENT 'Same as AR invoice: 3 draft, 8 submitted, 1 approved',
  user_id INT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_ar_cn_uniqid (credit_note_uniqid),
  KEY idx_ar_cn_customer (customer_id),
  KEY idx_ar_cn_invoice (ar_invoice_id),
  KEY idx_ar_cn_status (status_id),
  KEY idx_ar_cn_user (user_id),
  CONSTRAINT fk_ar_cn_invoice FOREIGN KEY (ar_invoice_id) REFERENCES ar_invoices (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ar_credit_note_lines (
  id INT AUTO_INCREMENT PRIMARY KEY,
  credit_note_id INT NOT NULL,
  line_no INT NOT NULL,
  ar_invoice_line_id INT NULL COMMENT 'Original ar_invoice_lines.id if copied from invoice',
  product_id INT NULL,
  item_name VARCHAR(512) NULL,
  description TEXT NULL,
  quantity DECIMAL(18,4) NOT NULL DEFAULT 0,
  uom_id INT NULL,
  rate DECIMAL(18,4) NOT NULL DEFAULT 0,
  tax_id INT NULL,
  tax_rate DECIMAL(18,4) NOT NULL DEFAULT 0,
  line_total DECIMAL(18,4) NOT NULL DEFAULT 0,
  account_id INT NULL,
  KEY idx_ar_cnl_cn (credit_note_id),
  CONSTRAINT fk_ar_cnl_cn FOREIGN KEY (credit_note_id) REFERENCES ar_credit_notes (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
