-- Create tbl_fund_transfer table for internal fund transfers between bank accounts
CREATE TABLE IF NOT EXISTS `tbl_fund_transfer` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `transfer_no` VARCHAR(50) NOT NULL UNIQUE COMMENT 'Auto-generated: TRF-000001',
  `from_bank_account_id` INT NOT NULL,
  `to_bank_account_id` INT NOT NULL,
  `transfer_date` DATE NOT NULL,
  `amount_from_currency` DECIMAL(18, 4) NOT NULL COMMENT 'Amount in from account currency',
  `from_currency_code` VARCHAR(10) NOT NULL,
  `to_currency_code` VARCHAR(10) NOT NULL,
  `rate_from_to_aed` DECIMAL(18, 6) NOT NULL COMMENT 'Rate: 1 from_currency = ? AED',
  `rate_to_to_aed` DECIMAL(18, 6) NOT NULL COMMENT 'Rate: 1 to_currency = ? AED',
  `amount_aed` DECIMAL(18, 4) NOT NULL COMMENT 'Amount in base currency (AED)',
  `amount_to_currency` DECIMAL(18, 4) NOT NULL COMMENT 'Amount received in to account currency',
  `rate_overridden` TINYINT(1) DEFAULT 0 COMMENT 'Whether user manually overrode the exchange rate',
  `reference` VARCHAR(255) NULL,
  `notes` TEXT NULL,
  `status_id` INT DEFAULT 3 COMMENT '3=Draft, 1=Approved, 8=Submitted for Approval, 2=Rejected',
  `approved_by` INT NULL,
  `approved_at` DATETIME NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `created_by` INT NULL,
  `updated_at` DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` INT NULL,
  FOREIGN KEY (`from_bank_account_id`) REFERENCES `acc_bank_details` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  FOREIGN KEY (`to_bank_account_id`) REFERENCES `acc_bank_details` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  FOREIGN KEY (`status_id`) REFERENCES `status` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  FOREIGN KEY (`created_by`) REFERENCES `user` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  FOREIGN KEY (`approved_by`) REFERENCES `user` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  INDEX `idx_transfer_no` (`transfer_no`),
  INDEX `idx_transfer_date` (`transfer_date`),
  INDEX `idx_from_account` (`from_bank_account_id`),
  INDEX `idx_to_account` (`to_bank_account_id`),
  INDEX `idx_status` (`status_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
